name: Semantic Release

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v5.0.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
